FROM node:14.3-alpine AS build
RUN apk update && apk add git
WORKDIR /usr/src/
RUN git clone https://github.com/backmeupplz/localizer-backend.git app
RUN cd app && yarn install && yarn build-ts && rm -rf node_modules/typescript

FROM node:14.3-alpine AS localizer-backend
WORKDIR /root/
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/package*.json .
COPY --from=build /usr/src/app/node_modules ./node_modules

CMD ["node", "dist/app.js"]