FROM node:14.3-alpine AS build
RUN apk update && apk add git
RUN git clone https://github.com/backmeupplz/localizer-frontend.git /usr/src/app
WORKDIR /usr/src/app
RUN yarn
RUN yarn exec vue-cli-service build

FROM node:14.3-alpine AS localizer-frontend
WORKDIR /root/
COPY --from=build /usr/src/app/dist .
RUN yarn global add serve

CMD ["serve", "-s", "."]